#+title: 指南

* 完整指南

/全面的书面指南即将推出!  订阅 [[file:../newsletter.org][System Crafters 新闻通讯]] 以在发布新指南时收到通知。/

* 视频系列

我创建了许多视频教程系列,以帮助您更深入地学习 GNU Emacs 和 GNU Guix!

*** Emacs 概要

[[../emacs-essentials/][Emacs 概要]]系列旨在教您关于 GNU Emacs 内置功能的所有知识。Emacs 初学者应该从这里开始,但经验丰富的 Emacs 用户也可能会学习一些隐藏的宝石!

*** 从零开始 Emacs

[[../emacs-from-scratch/][从零开始 Emacs]]系列适用于知道基础知识并现在想创建自己的现代 Emacs 配置的用户。我会逐步引导您通过使用许多内置或由 Emacs 社区提供的软件包来构建完全自定义的配置过程。

*** Emacs 桌面环境

[[../emacs-desktop-environment/][Emacs 桌面环境]]系列是一个更高级的课程,我将向您展示如何使用 Emacs 和 Linux 上的 EXWM 构建整个桌面环境。如果您真的想“生活”在 Emacs 中,这就是为您准备的!

*** 学习 Emacs Lisp

在 [[../learning-emacs-lisp/][学习 Emacs Lisp]]系列中,我会解释 Emacs 的核心定制语言 Emacs Lisp。我们从语言的基础知识开始,然后着手构建一个从头开始的 Emacs 软件包项目!

*** Emacs IDE

Emacs 也可以用作 IDE(集成开发环境),就像您可能习惯于其他编辑器一样。[[../emacs-ide/][Emacs IDE]]系列将向您展示如何设置 Emacs 作为 IDE,以获得许多语言的丰富开发功能!

*** Emacs 邮箱

Emacs 可以做许多事情,这个系列将向您展示如何使用它来管理您的电子邮件![[../emacs-mail/][Emacs 邮箱]]系列向您展示如何使用 mu4e 软件包来构建您能拥有的最高生产力的电子邮件工作流程。

*** Emacs 技巧

关于 Emacs,我们可以涵盖的有趣主题不需要专门的系列。[[../emacs-tips/][Emacs 技巧]]系列是一系列视频,将涵盖我们在其他系列中没有涉及的许多其他软件包和配置技巧!

*** 使用 Magit 精通 Git

在 Emacs 中最佳的 Git 界面就是 Magit! [[../mastering-git-with-magit/][使用 Magit 精通 Git]]系列将向您展示如何使用 Magit 使您的日常源代码控制操作变得超快!

*** 高级 Emacs 包管理

[[../advanced-package-management/][高级 Emacs 包管理]] 将教您更有效地使用 straight.el 等软件包管理器来管理 Emacs 包!

*** 在 Emacs 中构建第二大脑

Org Mode 使我们能够在 Emacs 中组织生活,但我们可以通过使用 Org Roam 等工具在 Emacs 中构建个人知识库来进一步发展! [[../build-a-second-brain-in-emacs/][在 Emacs 中构建第二大脑]]系列将向您展示如何使用这些优秀的软件包构建个人知识管理和生产力工作流程。

*** 使用 Org Mode 发布网站

Org Mode 有能力导出各种其他格式,包括 HTML。我们可以利用这种功能直接从 Emacs Org Mode 发布网站。[[../publishing-websites-with-org-mode/][使用 Org Mode 发布网站]]系列将向您展示如何使用 Emacs Lisp 构建和发布网站,就像您现在正在阅读的网站一样,所有内容都来自 Org Mode 文件!

*** 使用 Emacs 聊天

想从 Emacs 的舒适环境与各种自由开源软件项目的社区进行聊天吗?[[../chatting-with-emacs/][使用 Emacs 聊天]]系列将教您如何做到这一点!
** GNU Guix

*** 使用 GNU Guix 打造您的系统

GNU Guix 是一个惊人的工具,不仅可以管理您使用的程序,还可以管理整个系统配置。[[../craft-your-system-with-guix/][使用 GNU Guix 打造您的系统]]系列将逐步介绍学习和使用 Guix 的过程,以便您可以打造自己的可重复系统配置!
