#+title: Welcome!

System Crafters 是一个专门为那些有兴趣通过 *增加使用乐趣和生产力* 来设计自己的计算体验的计算机爱好者学习和资源社区。

这个网站旨在成为互联网上学习如何利用 [[https://www.gnu.org/software/emacs/][GNU Emacs]]、[[https://guix.gnu.org/][GNU Guix]] 和 [[https://en.wikipedia.org/wiki/Linux][GNU/Linux]] 等工具来使用自由软件工具完全定制工作流程的最全面参考资料!

[[https://youtube.com/@SystemCrafters][System Crafters YouTube 频道]] 也包含近 200 个视频和现场流录制,演示和解释这些工具和更广泛的主题!

* 开始!

如果您刚开始使用 *GNU Emacs* 并想了解基础知识,请查看 [[file:emacs-essentials/absolute-beginners-guide-to-emacs.org][Emacs 绝对初学者指南]]!

从那里开始,查看 [[file:emacs-essentials.org][Emacs 要点]] 系列以了解使用 Emacs 的基础知识,然后按照 [[file:emacs-from-scratch.org][Emacs 白板]] 系列学习如何构建一个您理解的现代 Emacs 配置!

一旦您熟悉使用 Emacs,请通过查看 [[file:craft-your-system-with-guix.org][用 GNU Guix 打造你的系统]] 系列学习如何使用 *GNU Guix* 来制作完整的、可重现的系统配置!

您还可以查看我创建的许多 [[file:videos.org][视频系列]] ,以帮助您深入学习这些工具。

* 需要帮助?

如果您需要帮助特定主题,有几个资源可以考虑:

- 各种主题的常见问题解答页面,如 [[file:faq/emacs.org][Emacs]] 和 [[file:faq/guix.org][Guix]]
- 加入 [[file:community.org][System Crafters 聊天]] 与社区讨论
- [[/how-to-help/#support-my-work][每月捐赠者]] 5 美元或更高级别可以在专用讨论列表上提问!

* 直播

加入我们 *每周五* 的常规节目 *[[file:live-streams.org][System Crafters Live!]]*。该流程在 [[https://youtube.com/@SystemCrafters][YouTube]] 和 [[https://twitch.tv/SystemCrafters][Twitch]] 上播出。

在这些流程中,我们通常会尝试新的软件包,配置和定制,以了解使用它们的优点和缺点。其他时候,我们会对软件、计算和生产力进行哲学讨论。这总是很开心的时刻!

[[https://time.is/compare/1800_in_Athens][点击这里]] 查看您当地时区的流时间!

* 保持最新!

查看最新的 [[/news][新闻页面]] 以查看网站和社区的最新更新。您也可以订阅网站各个部分的 [[/rss][RSS 源]]。

一个更好的选择是订阅下面的 [[file:newsletter.org][System Crafters 通讯]]!
